# Set up the world

In [13]:
import numpy as np
import random

In [14]:
states = [0, 1, 2, 3, 4, 5]
actions = ['up', 'right', 'left']
gamma = 0.9  # discount factor
terminal_states = [0]

## Q1: set up Q-table

What is the dimension of the Q table? (hint: how many states are there? how many actions are there?)

What should be the initial value of the `Q[s,a]`? (0 or $-\infin$?) Justify yourself.

In [15]:
def init_Q():
    # put your code here...
    Q = np.zeros([2,3,3])
    
    return Q

Q = init_Q()

## Q2: select action function

Please refer to the 4th class material to implement the action selection function.

In [18]:
def random_select(state):
    # select random action and return
    # put your code here...
    action = random.choice(actions)
	return action
    

def greedy_select(state, Q):
    # select the action that looks the best right now according to the Q table.
    # put your code here...
    max_action = None
    max_Q = 0
    for a in actions:
        if Q[state, a] > max_Q:
            max_Q = Q[state, a]
            max_action = a
    return max_action

def sometimes_random_select(state, Q, p):
    # for probability p, be greedy. for probability (1 - p), be random.
    # put your code here...
    prob = random.rand(0, 1)  # random number between 0 and 1
	if prob < p:
		return greedy_select(s)
	else:
		return random_select(s)
    

TabError: inconsistent use of tabs and spaces in indentation (2783767007.py, line 5)

## Q3: Move function

According to the description given, implement the move function: it should take
the current state and action as input and return the reward and next state.

In [10]:
def move(state, action):
    # action "up" is implemented for you as an example.
    if action == 'up':
        reward = -1
        if state in (4, 5):
            next_state = state
        else:
            next_state = state + 2

    elif action == 'left':
        # put your code here...
        if state in (1, 3, 5):
            reward = 0
            next_state = state - 1
        elif state in (0):
            reward = -1
            next_state = state
        elif state in (2):
            reward = -100
            next_state = state
        else:
            reward = 10
            next_state = 0
    elif action == 'right':
        # put your code here...
        if state in (0, 2, 4):
            reward = 0
            next_state = state + 1
        else:
            reward = -1
            next_state = state

    
    return reward, next_state


## Q4: Q learning

Implement the Q learning algorithm using the `sometimes_random_select` and `move` function.


In [19]:
def Q_learning(num_episodes, Q, gamma=0.9, p=0.8):
    for i in range(num_episodes):
        s = random.choice(states[1:])  # do not include s0
        while True:
            # 1. select action
            # put your code here...
            a = sometimes_random_select(state, Q, p)
            
            # 2. move
            # put your code here...
            reward, next_state = move(s, a)

            # 3. update the Q table
            # put your code here...
            values = []
		    for next_a in actions:
			    values.append(Q[next_state, next_a])

		    Q[s, a] = reward + gamma * max(values)

            if next_state in terminal_states:
                break


TabError: inconsistent use of tabs and spaces in indentation (3834537648.py, line 16)

In [20]:
# run Q learning

Q_learning(1000, Q, gamma=gamma, p=0.8)

NameError: name 'Q_learning' is not defined

In [21]:
print(Q)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Q5: Try Q learning with different number of episodes. How does it affect the final Q-table?

In [ ]:
number_of_episodes = []  # put your code here...
for n in number_of_episodes:
    Q = init_Q()
    Q_learning(n, Q, gamma=gamma, p=0.8)
    print(Q)

Write your observiation here.